apache/arrow-java

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/usage_question.yaml
These files are copied from apache/arrow with component options removed.
Closes #21
> GH-21: Add issue template

- .env
- .github/workflows/java.yml
- .github/workflows/test.yml
- .gitignore
- .gitmodules
- arrow-format/File.fbs
- arrow-format/Flight.proto
- arrow-format/FlightSql.proto
- arrow-format/Message.fbs
- arrow-format/README.rst
- arrow-format/Schema.fbs
- arrow-format/SparseTensor.fbs
- arrow-format/Tensor.fbs
- arrow-format/substrait/extension_types.yaml
- ci/scripts/java_build.sh
- ci/scripts/java_test.sh
- dataset/pom.xml
- docker-compose.yml
- flight/flight-core/pom.xml
- flight/flight-sql-jdbc-core/pom.xml
- tools/src/test/java/org/apache/arrow/tools/TestIntegration.java
- tools/src/test/resources/integration_json_simple.json
- tools/src/test/resources/integration_json_struct.json
- vector/src/test/java/org/apache/arrow/vector/ipc/TestJSONFile.java
- vector/src/test/resources/integration_json_struct.json
> GH-6: Add Linux test CI

- .github/workflows/test.yml
Update latest Java version used by Github workflows to Java 23.
> MINOR: Update latest java version to 23

- dataset/src/test/java/org/apache/arrow/dataset/TestAllTypes.java
https://github.com/apache/arrow/commit/ded148c2ef5dd441a3b6ab9496d0ed0aeb940f71 was merged after the migration.
Fixes #447.
> GH-447: Port fix from apache/arrow that was missed

- .github/workflows/test.yml
> GH-16: Add integration test CI

- flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlClient.java
> GH-483: Use ArrowReader instead of ArrowStreamReader in FlightSqlClient.executeIngest method

- .github/workflows/rc.yml
- .github/workflows/release.yml
- dev/release/README.md
- dev/release/bump_version.sh
- dev/release/release.sh
- dev/release/release_rc.sh
- dev/release/verify_rc.sh
Fixes GH-20.
This is based on https://github.com/apache/arrow-go/pull/122 .
Workflow:
Cut a RC:
1. Bump version by `dev/release/bump_version.sh 19.0.0`
2. Run `dev/release/release_rc.sh`
1. `dev/release/release_rc.sh` pushes `v${version}-rc${rc}` tag
2. `.github/workflows/rc.yml` creates `apache-arrow-java-${version}.tar.gz{,.sha256,.sha512}`
3. `.github/workflows/rc.yml` uploads `apache-arrow-java-${version}.tar.gz{,.sha256,.sha512}` to GitHub Releases
4. `dev/release/release_rc.sh` downloads `apache-arrow-java-${version}.tar.gz` from GitHub Releases
5. `dev/release/release_rc.sh` signs `apache-arrow-java-${version}.tar.gz` as `apache-arrow-go-${version}.tar.gz.asc`
6. `dev/release/release_rc.sh` uploads `apache-arrow-java-${version}.tar.gz.asc` to GitHub Releases
3. Start a vote
(GitHub …
> GH-20: Add release scripts

- dev/release/release.sh
Fixes GH-512.
We can't use `svn add .` here. If we use `.`, we'll get the following error:
svn: warning: W150002: '/tmp/arrow-java/dev/release/dist' is already under version control
svn: E200009: Could not add all targets because some targets are already versioned
svn: E200009: Illegal target for the requested operation
> GH-512: [Release] Fix `svn add` target

- vector/src/main/java/org/apache/arrow/vector/FixedSizeBinaryVector.java
- vector/src/main/java/org/apache/arrow/vector/LargeVarBinaryVector.java
- vector/src/main/java/org/apache/arrow/vector/LargeVarCharVector.java
- vector/src/main/java/org/apache/arrow/vector/ValueVector.java
- vector/src/main/java/org/apache/arrow/vector/VarBinaryVector.java
- vector/src/main/java/org/apache/arrow/vector/VarCharVector.java
- vector/src/main/java/org/apache/arrow/vector/ViewVarBinaryVector.java
- vector/src/main/java/org/apache/arrow/vector/ViewVarCharVector.java
> GH-469: Unify `ValueVector.getObject` and `VariableWidthFieldVector.get` behavior about null value

- .pre-commit-config.yaml
> GH-518: Cleanup apache-arrow-java.tar.gz created by pre-commit

- .github/workflows/test.yml
- .mvn/develocity.xml
This PR migrates the Arrow project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
Additionally, this PR sets a projectId for use by Develocity.
Fixes #515
> GH-515: Publish build scans to develocity.apache.org

- .cmake-format.py
- .pre-commit-config.yaml
Fixes GH-520.
The configuration file is borrowed from apache/arrow.
> GH-520: [CI] Add cmake-format to pre-commit

- .gitignore
- ci/scripts/jni_full_build.sh
- dev/release/release_rc.sh
> GH-522: [Release] Add support for signing .jar

- .github/workflows/rc.yml
Apache Arrow 19.0.0 has been released.
> GH-525: [Release] Use released Apache Arrow C++ for RC CI

- .github/workflows/rc.yml
- .pre-commit-config.yaml
- ci/scripts/download_cpp.sh
- ci/scripts/jni_build.sh
- ci/scripts/jni_macos_build.sh
- ci/scripts/jni_windows_build.sh
- ci/scripts/util_log.sh
Fixes GH-527.
It seems that arrow-testing with ARROW_BUILD_STATIC=ON and GTest_SOURCE=BUNDLED is broken. We'll enable JNI test after we fix it in apache/arrow.
> GH-527: [Release] Add support for .jar for Windows

- .github/workflows/rc.yml
> GH-531: [Release] Add support for .jar for arm64 Linux

- dev/release/README.md
Fixes GH-533.
This is borrowed from ADBC:
https://arrow.apache.org/adbc/current/development/releasing.html
> GH-533: [Release] Add a post release task for publishing staged .jar

- LICENSE.txt
- NOTICE.txt
- dev/checkstyle/suppressions.xml
- memory/memory-core/src/main/java/org/apache/arrow/util/Preconditions.java
- pom.xml
- vector/src/main/java/org/apache/arrow/vector/util/IntObjectHashMap.java
- vector/src/main/java/org/apache/arrow/vector/util/IntObjectMap.java
The files **IntObjectMap.java** and **IntObjectHashMap.java** are sourced from:
https://github.com/netty/netty/tree/netty-4.1.117.Final/common/src/main/templates/io/netty/util/collection/
(Specific types will be generated during the compilation phase, but fundamentally, no change in intellectual property ownership has occurred.)
The Guava code is sourced from:
https://github.com/google/guava/blob/v33.4.0/guava/src/com/google/common/base/Preconditions.java
Given the possibility of changes to the license, the specific version has been noted to help reduce ambiguity.
close #549
> GH-549: Fix Incorrect NOTICE File and Update LICENSE Headers for Third-Party Code Compliance

- vector/src/main/java/org/apache/arrow/vector/util/VectorAppender.java
- vector/src/test/java/org/apache/arrow/vector/TestUtils.java
- vector/src/test/java/org/apache/arrow/vector/TestVariableWidthViewVector.java
- vector/src/test/java/org/apache/arrow/vector/testing/ValueVectorDataPopulator.java
- vector/src/test/java/org/apache/arrow/vector/util/TestVectorAppender.java
> GH-48: Implement VectorAppender for BaseVariableWidthViewVector

- .asf.yaml
- .github/workflows/rc.yml
Fixes #537.
This also enables preview in fork at
`https://${YOUR_GITHUB_ACCOUNT}.github.io/arrow-java/main/` after you enable GitHub Pages on `gh-pages` branch at
`https://github.com/${YOUR_GITHUB_ACCOUNT}/arrow-java/settings/pages`.
> GH-547: [CI][Docs] Publish docs to https://arrow.apache.org/java/main/ on push

- vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthViewVector.java
> GH-41: BaseVariableWidthViewVector setZero only if necessary

- .asf.yaml
> GH-570: [Docs] Use https://arrow.apache.org/java/ as the official site URL

- .github/workflows/rc.yml
- .github/workflows/release.yml
- dev/release/release_rc.sh
> GH-548: [Release][Docs] Publish docs to https://arrow.apache.org/java/current/ on release

- .htaccess
> GH-571: [Docs] Redirect https://arrow.apache.org/java/ to https://arrow.apache.org/java/current/

- .asf.yaml
We can add collaborator in the `.asf.yaml`. A collaborator can be assigned to GitHub Issue for instance.
> MINOR: Add jbonofre to collaborators

- .htaccess
Fixes #571.
We need to use `^/java/$` not `^/$` because we deploy our website to `https://.../java/` not `https://.../`.
> GH-571: [Docs] Fix redirect pattern

- dev/release/release_rc.sh
Fixes GH-588.
`release.yml` takes at least 30min now. So 60s wait interval is too short. We can use longer interval to avoid needless API requests.
> GH-588: [Release] Increase wait interval in `dev/release/release_rc.sh`

- .github/workflows/rc.yml
According to https://github.com/cli/cli/issues/9586, GitHub CLI doesn't respect the GitHub rate limits and GitHub is uninterested in fixing this.
> MINOR: Upload release artifacts individually with sleep

- .github/workflows/rc.yml
We don't checkout apache/arrow-java in this job. So we need to specify --repo explicitly.
> MINOR: Specify --repo explicitly

- dev/release/release.sh
Fixes GH-603.
Message from Git:
hint: You have created a nested tag. The object referred to by your new tag is
hint: already a tag. If you meant to tag the object that it points to, use:
hint:
hint: 	git tag -f v18.2.0 v18.2.0-rc5^{}
hint: Disable this message with "git config advice.nestedTag false"
> GH-603: [Release] Suppress a nested tag warning in `dev/release/release.sh`

- dev/release/release.sh
Fixes GH-605.
If `dev/release/release.sh` shows what should we do at repository.apache.org, it's helpful.
> GH-605: [Release] Show the repository.apache.org step

- dev/release/release.sh
Fixes GH-604.
For example, here are target files for 18.2.0:
* apache-arrow-java-18.2.0.tar.gz
* apache-arrow-java-18.2.0.tar.gz.asc
* apache-arrow-java-18.2.0.tar.gz.sha256
* apache-arrow-java-18.2.0.tar.gz.sha512
> GH-604: [Release] Upload only source archive to dist.apache.org

- .github/workflows/release.yml
The GitHub CLI does not respect GitHub API rate limits and will not fix this (https://github.com/cli/cli/issues/9586).
Closes #609.
> GH-609: [Release] Wait between artifact uploads

- docs/source/conf.py
> GH-611: [Docs] Detect version from pom.xml

- .github/pull_request_template.md
- .github/release.yml
- .github/workflows/dev_pr.js
- .github/workflows/dev_pr.yml
- CONTRIBUTING.md
- Validate that at least one of certain labels are present on a PR.
- Validate the format of the title.
- Add label for things that are not dependencies but are other chores (release/build work).
- Add label for documentation updates.
- Validate that a PR titled `GH-499` is actually linked to issue `#499` by poking the GitHub API.
- Add the GitHub config to use these labels for changelog generation.
Closes #499.
> GH-499: Require PR labels for changelog

- .env
- .github/workflows/rc.yml
- compose.yaml
- gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/FilterProjectTest.java
- gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/FilterTest.java
- gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/ProjectorDecimalTest.java
- gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/ProjectorTest.java
Fixes GH-55.
I fixed the linking error here: https://github.com/apache/arrow/pull/45114/
Reenabling some disabled tests.
Yes, they are tests.
No.
> GH-55: [Gandiva] Re-enable tests

- gandiva/src/main/java/org/apache/arrow/gandiva/evaluator/Projector.java
Multiple threads can attempt to create the same llvm expression in Gandiva. This isn't allowed with the new JIT compiler, so synchronizing will prevent this scenario.
Synchronize some methods to avoid adding duplicate llvm expressions.
Yes, through unit tests in Gandiva.
No.
Closes GH-601
> GH-601: [Gandiva] Synchronize some methods on the Projector

- dev/release/README.md
Add instructions for undocumented post-release tasks.
Closes #629.
> GH-629: Add post-release tasks to dev/release/README.md

- vector/src/main/java/org/apache/arrow/vector/types/Types.java
- vector/src/test/java/org/apache/arrow/vector/TestMapVector.java
> GH-625: Map MinorType getNewFieldWriter returns UnionMapWriter

- .github/workflows/dev.yml
- .github/workflows/rc.yml
- .github/workflows/test.yml
Upgrade to GitHub actions/cache 4.2.2 as previous versions are deprecated.
> MINOR: Upgrade to GitHub actions/cache 4.2.2

- vector/src/main/java/org/apache/arrow/vector/VectorLoader.java
When `VectorLoader` tries to load buffers (i.e., `loadBuffers`), it has detect on the error case that some buffers are not consumed. But another error that the number of buffers is less than expected is not handled for now. Once it is happened, users will get `java.util.NoSuchElementException` which is not easy to understand.
This patch adds an explicit exception for such case.
See more discussion at #648.
> MINOR: Add explicit exception when no more buffer can be read when loading buffers

- flight/flight-integration-tests/src/shade/LICENSE.txt
- flight/flight-integration-tests/src/shade/NOTICE.txt
- flight/flight-sql-jdbc-driver/src/shade/LICENSE.txt
- flight/flight-sql-jdbc-driver/src/shade/NOTICE.txt
- tools/src/shade/LICENSE.txt
- tools/src/shade/NOTICE.txt
- vector/src/shade/LICENSE.txt
Align versions in `LICENSE`/`NOTICE` in regards of the recent dependency updates.
> MINOR: Update versions in LICENSE/NOTICE

- flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java
- flight/flight-core/src/main/java/org/apache/arrow/flight/FlightGrpcUtils.java
- flight/flight-core/src/main/java/org/apache/arrow/flight/grpc/NettyClientBuilder.java
Expose the internal gRPC channel builder in the FlightClient so that applications can build on top of it without having to replicate all the special Flight logic. This makes it much easier to apply some gRPC tweaks without duplicating Arrow code.
Closes #81.
> GH-81: [Flight] Expose gRPC in Flight client builder

- .github/workflows/dev_pr.yml
- .github/workflows/dev_pr_milestone.sh
Derived from the ADBC one.
Fixes #456.
> GH-456: Add action to assign milestone to PR/issue

- flight/flight-sql-jdbc-core/pom.xml
- pom.xml
Use Mockito BoM for dependencies instead of individual versions.
> MINOR: Use mockito bom and upgrade to Mockito 5.16.0

- vector/src/main/codegen/templates/UnionVector.java
- vector/src/test/java/org/apache/arrow/vector/complex/impl/TestPromotableWriter.java
When a DecimalVector is promoted to a UnionVector via a PromotableWriter, the UnionVector will have the decimal vector in it's internal struct vector, but the decimalVector field will not be set. If UnionReader.read is then used to read from the UnionVector, it will fail when it tries to read one of the promoted decimal values, due to decimalVector being null, and the exact decimal type not being provided.  This failure is unnecessary though as we have a pre-existing decimal vector, the caller just does not know the exact type - and it shouldn't be required to.
The change here is to check for a pre-existing decimal vector in the internal struct when getDecimalVector() is called.  If one exists, set the decimalVector field and return.  Otherwise, if none exists, throw the exception. …
> GH-655: Failure in UnionReader.read after DecimalVector promotion to UnionVector

- ci/scripts/jni_macos_build.sh
Update a sanity check in CI that's incorrectly failing the macOS JNI builds.
> MINOR: Fix macOS JNI build

- .github/workflows/rc.yml
- dataset/src/main/cpp/jni_util.cc
- gandiva/src/main/cpp/expression_registry_helper.cc
- gandiva/src/main/cpp/jni_common.cc
Upstream renamed the public DCHECK macros to ARROW_DCHECK (https://github.com/apache/arrow/pull/46015)
> MINOR: Fix JNI code after upstream DCHECK change

- c/src/test/java/org/apache/arrow/c/RoundtripTest.java
- vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java
- vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java
This patch fixes the initialization of offset buffers when exporting variable width arrays through Arrow C Data Interface. The original code incorrectly mess up with the member `this.offsetBuffer` while we should actually initialize the newly allocated offsetBuffer. I think the diff itself will be quite self-explanatory.
Closes #704 and probably #88 .
> GH-704: Fix initialization of offset buffer when exporting VarChar vectors through C Data Interface

- flight/flight-sql-jdbc-core/pom.xml
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightConnection.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowFlightConnectionConfigImpl.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ResultSetTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandlerBuilderTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/ArrowFlightConnectionConfigImplTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/FallbackFlightSqlProducer.java
Allow configuring the connect timeout via `connectTimeoutMs` so that the driver doesn't wait so long before giving up on unreachable locations.
Fixes #494.
> GH-494: [Flight] Allow configuring connect timeout in JDBC

- .asf.yaml
Enable GitHub Discussions like other Arrow repositories.
Fixes #708.
> GH-708: Enable GitHub discussions

- c/src/main/java/org/apache/arrow/c/BufferImportTypeVisitor.java
For variable-size binary layout arrays, BufferImportTypeVisitor currently derives the length of the value buffer by calculating the difference between the last and first offset. When the first offset is not zero, this is actually incorrect and leads to out of bounds errors when attempting to read values from the imported array.
Instead, BufferImportTypeVisitor should simply use the last offset value as the length of the value buffer. This PR makes that change.
Just FYI, I bumped into this issue when attempting to import an array originating from DataFusion. A test query of the form `SELECT column1 FROM VALUES ('a'), ('b'), ('c'), ('d') LIMIT 2 OFFSET 1;` returns a slice of the full set of values. The values buffer contains all the original values, and the offsets buffer contains 1 and 2 …
> GH-709: Correct length calculation of value buffers of variable-sized arrays

- .github/workflows/rc.yml
- ci/scripts/jni_macos_build.sh
- ci/scripts/jni_manylinux_build.sh
There is no more need after
https://github.com/apache/arrow/commit/32641ecfd97e302ea8119b1147d77aced96d097b
> MINOR: Don't uninstall Flatbuffers in CI

- pom.xml
- vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java
- vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthViewVector.java
- vector/src/test/java/org/apache/arrow/vector/TestValueVector.java
- vector/src/test/java/org/apache/arrow/vector/TestVectorReAlloc.java
- vector/src/test/java/org/apache/arrow/vector/util/TestVectorAppender.java
Allow actually reaching MAX_BUFFER_SIZE at reallocating variable width vectors instead of exceeding it calculating the next power of 2.
For unit testing the maximum allocation size has be increased to 2MB - 1byte to simulate the default maximum behavior. Due to this change needed some updates in existing unit tests because of the round ups used at calculating the required buffer sizes.
Closes #721.
> GH-721: Allow using 1GB+ data buffers in variable width vectors

- dev/release/.env.example
- dev/release/README.md
- dev/release/bump_version.sh
- dev/release/release.sh
- dev/release/release_rc.sh
Add missing `dev/release/.env` description to `dev/release/README.md`.
This also moves `GH_TOKEN` to `dev/release/.env`.
Closes #587.
> GH-587: [Release] Add .env description to dev/release/README.md

- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/accessor/impl/calendar/ArrowFlightJdbcDateVectorAccessor.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/accessor/impl/calendar/ArrowFlightJdbcTimeStampVectorAccessor.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/accessor/impl/calendar/ArrowFlightJdbcTimeVectorAccessor.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/SqlTypes.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowDatabaseMetadataTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/accessor/impl/calendar/ArrowFlightJdbcTimeStampVectorAccessorTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/SqlTypesTest.java
This PR adds support for natively fetching `java.time.*` objects through the JDBC driver.
DateVector
- getObject(LocalDate.class)
DateTimeVector
- getObject(OffsetDateTime.class)
- getObject(LocalDateTime.class)
- getObject(ZonedDateTime.class)
- getObject(Instant.class)
TimeVector
- getObject(LocalTime.class)
This PR also changes the behavior for vectors that include TZ info. These will now return as `TIMESTAMP_WITH_TIMEZONE`. 
The behavior for different ways to access a TimeStampVector are as follows:
|                                 | Vector with TZ                                                                                             | Vector W/O TZ                                                                             | …
> GH-463: Improve TZ support for JDBC driver

- adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/BinaryConsumer.java
- adapter/jdbc/src/test/java/org/apache/arrow/adapter/jdbc/consumer/BinaryConsumerTest.java
Set `startOffset` of the next item when `BinaryConsumer` consuming `null` value.
Closes #729 .
> GH-729: [JDBC] Fix BinaryConsumer consuming null value

- arrow-format/FlightSql.proto
- flight/flight-integration-tests/src/main/java/org/apache/arrow/flight/integration/tests/FlightSqlScenarioProducer.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowDatabaseMetadata.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ConvertUtils.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowDatabaseMetadataTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/ConvertUtilsTest.java
- flight/flight-sql/src/main/java/org/apache/arrow/flight/sql/FlightSqlColumnMetadata.java
Resolves #737 
This is a draft implementation of https://github.com/apache/arrow/pull/46110 for Java
> GH-737: [FlightSQL] Allow returning column remarks in FlightSQL's CommandGetTables

- pom.xml
As discussed, better to stay with Netty 4.1.x for now (regarding gRPC).
> MINOR: Revert "MINOR: Bump io.netty:netty-bom from 4.1.119.Final to 4.2.0.Final (#700)"

- flight/flight-sql-jdbc-core/pom.xml
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightConnection.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/utils/FlightClientCache.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/utils/FlightLocationQueue.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/ArrowFlightConnectionConfigImpl.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ResultSetTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandlerBuilderTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/utils/FlightClientCacheTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/utils/FlightLocationQueueTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/utils/ArrowFlightConnectionConfigImplTest.java
Instead of repeatedly trying to access locations which have failed before, cache them and move them to the end of the list of locations to attempt on subsequent accesses. This provides a better user experience for Flight SQL services that return multiple locations in the expectation that the user may not be able to access some of them (but would have a better experience if they are).
Requires #494.
Closes #661.
> GH-661: [Flight] JDBC: Cache failed locations

- dev/release/release.sh
`dev/release/release.sh` requires `SOURCE_DIR` to locate `.env` but it is missing.
> MINOR: add missing SOURCE_DIR in dev/release/release.sh

- flight/flight-core/src/main/java/org/apache/arrow/flight/ArrowMessage.java
In some cases 
[InflaterInputStream](
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/zip/InflaterInputStream.html) can return a non zero on `available()` method call, while it is actually at EOS. A subsequent `read()` call would respond with -1 and eventually cause:
<pre>
Caused by: org.apache.arrow.flight.FlightRuntimeException: Failed to read message.
at org.apache.arrow.flight.CallStatus.toRuntimeException(CallStatus.java:121)
at org.apache.arrow.flight.grpc.StatusUtils.fromGrpcRuntimeException(StatusUtils.java:161)
at org.apache.arrow.flight.grpc.StatusUtils.fromThrowable(StatusUtils.java:182)
at org.apache.arrow.flight.FlightStream$Observer.onError(FlightStream.java:489)
at org.apache.arrow.flight.FlightClient$1.onError(FlightClient.java:371)
at …
> MINOR: Empty stream double check

- vector/src/main/java/org/apache/arrow/vector/compare/RangeEqualsVisitor.java
- vector/src/main/java/org/apache/arrow/vector/complex/RunEndEncodedVector.java
- vector/src/test/java/org/apache/arrow/vector/TestRunEndEncodedVector.java
- vector/src/test/java/org/apache/arrow/vector/compare/TestRangeEqualsVisitor.java
Avoid doing a binary search on every step to make the RangeEqualsVisitor of RunEndEncodedVector more efficient.
Closes #52 .
> GH-52: Make RangeEqualsVisitor of RunEndEncodedVector more efficient

- .github/workflows/test.yml
`js/` in apache/arrow moved to apache/arrow-js. So let's use apache/arrow-js for JS.
Closes #768.
> GH-768: Use apache/arrow-js for JS in integration test

- .github/workflows/rc.yml
If we update older Python (e.g. Python 3.12) to newer Python (e.g. Python 3.13), depended packages may update newer Python when we update old Python.
Let's use newer Python -> older Python order instead to avoid the situation. 
Closes #770.
> GH-770: Ensure updating Homebrew Python on macos-13

- flight/flight-sql/pom.xml
- flight/flight-sql/src/test/java/org/apache/arrow/flight/sql/test/TestFlightSql.java
- flight/flight-sql/src/test/java/org/apache/arrow/flight/sql/test/TestFlightSqlStateless.java
- flight/flight-sql/src/test/java/org/apache/arrow/flight/sql/test/TestFlightSqlStreams.java
Series of PRs to consolidate on using `assertj` in tests as part of https://github.com/apache/arrow-java/issues/70.
> GH-70: Move from `hamcrest` to `assertj` in `flight-sql`

- .github/workflows/dev_pr.yml
This step needs permissions to write to issues so we can set the milestone.
> MINOR: Add missing permission to milestone assignment bot

- vector/src/main/java/org/apache/arrow/vector/BaseFixedWidthVector.java
- vector/src/main/java/org/apache/arrow/vector/BaseLargeVariableWidthVector.java
- vector/src/main/java/org/apache/arrow/vector/BaseValueVector.java
- vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthVector.java
- vector/src/main/java/org/apache/arrow/vector/BaseVariableWidthViewVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/BaseLargeRepeatedValueViewVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/BaseRepeatedValueVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/BaseRepeatedValueViewVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/FixedSizeListVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/LargeListVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/LargeListViewVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/ListVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/ListViewVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/MapVector.java
Move `splitAndTransferValidityBuffer` up to `BaseValueVector`.
This PR is not touching the implementation of this function in `StructVector` -- that is not being derived from `BaseValueVector` so some amount of duplication is probably fine.
Closes #79
> GH-79: Move `splitAndTransferValidityBuffer` to `BaseValueVector`

- adapter/avro/src/main/java/org/apache/arrow/adapter/avro/ArrowToAvroUtils.java
- adapter/avro/src/main/java/org/apache/arrow/adapter/avro/producers/AvroEnumProducer.java
- adapter/avro/src/main/java/org/apache/arrow/adapter/avro/producers/DictionaryDecodingProducer.java
- adapter/avro/src/test/java/org/apache/arrow/adapter/avro/ArrowToAvroDataTest.java
- adapter/avro/src/test/java/org/apache/arrow/adapter/avro/ArrowToAvroSchemaTest.java
- adapter/avro/src/test/java/org/apache/arrow/adapter/avro/RoundTripDataTest.java
- adapter/avro/src/test/java/org/apache/arrow/adapter/avro/RoundTripSchemaTest.java
Updated ArrowToAvro to output dictionary-encoded string vectors as Avro enums, where possible. Apologies for the delay - busy as usual!
To output dict encoded vectors as enums, a dictionary provider must be supplied to the top level methods with all the required dictionaries. All dictionary values must be present when the schema is written, i.e. before the data blocks are produced. If data is being written as a schema followed by multiple blocks, values added to a dictionary in between blocks will not be included in the schema resulting in an invalid Avro file (in general supply an invalid dictionary mapping will result in invalid output).
Dictionary encoded fields are checked to ensure they are valid Avro enums. If the dictionary encoded field is not a string field, or the string values …
> GH-731: Avro adapter, output dictionary-encoded fields as enums

- flight/flight-core/src/main/java/org/apache/arrow/flight/grpc/NettyClientBuilder.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightConnection.java
- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcConnectionCookieTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ConnectionTest.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/FlightServerTestExtension.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandlerBuilderTest.java
* Driver version is passed on to NettyBuilderClient to append it to the user-agent header
* NettyBuilderClient now prepends `JDBC Flight SQL Client <version>` to the header (e.g. `JDBC Flight SQL Client 19.0.0-SNAPSHOT grpc-java-netty/1.73.0`)
Closes #804.
> GH-804: Prepend JDBC FlightSQL version to user agent

- flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightMetaImpl.java
- flight/flight-sql-jdbc-core/src/test/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatementTest.java
Instead of always obtaining a result set for queries issued via
PreparedStatement.execute(), we now inspect the dataset_schema
returned in ActionCreatePreparedStatementResult. If the schema has no
fields, we retrieve the update count instead. This aligns the return
value with the expectations of the JDBC API.
For such cases, the Arrow Flight SQL path now uses
CommandPreparedStatementUpdate instead of
CommandPreparedStatementQuery. This change mirrors the existing
approach in Statement.execute() and Statement.executeUpdate().
Yes
Closes #797.
> GH-797: [JDBC] Fix PreparedStatement#execute for DML/DDL

- adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/CompositeJdbcConsumer.java
- adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/consumer/exceptions/JdbcConsumerException.java
Turns out not all MinorTypes have a corresponding ArrowType, which can cause the following exception while handling the original exception:
```
Caused by: java.lang.UnsupportedOperationException: Cannot get simple type for type DECIMAL
at org.apache.arrow.vector.types.Types$MinorType.getType(Types.java:815)
at org.apache.arrow.adapter.jdbc.consumer.CompositeJdbcConsumer.consume(CompositeJdbcConsumer.java:49)
```
This PR changes the value we store in the exception to be the `MinorType` instead so we can still get useful info about the type but avoiding this possible exception.
Closes #858.
> GH-858: Fix error handling in CompositeJdbcConsumer

- vector/src/main/codegen/includes/vv_imports.ftl
- vector/src/main/codegen/templates/AbstractFieldReader.java
- vector/src/main/codegen/templates/BaseReader.java
- vector/src/main/codegen/templates/ComplexCopier.java
- vector/src/main/codegen/templates/NullReader.java
- vector/src/main/java/org/apache/arrow/vector/BaseValueVector.java
- vector/src/main/java/org/apache/arrow/vector/NullVector.java
- vector/src/main/java/org/apache/arrow/vector/ValueVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/AbstractContainerVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/LargeListVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/LargeListViewVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/ListVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/ListViewVector.java
- vector/src/main/java/org/apache/arrow/vector/complex/impl/AbstractBaseReader.java
- vector/src/main/java/org/apache/arrow/vector/complex/impl/UnionExtensionWriter.java
- vector/src/main/java/org/apache/arrow/vector/complex/impl/UnionLargeListReader.java
- vector/src/test/java/org/apache/arrow/vector/TestListVector.java
- vector/src/test/java/org/apache/arrow/vector/TestMapVector.java
- vector/src/test/java/org/apache/arrow/vector/complex/impl/TestComplexCopier.java
- vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidReaderImpl.java
Updated ComplexCopier to support ExtensionType - it contains two **copy** methods 
```
public static void copy(FieldReader input, FieldWriter output) //for not breaking  existing logic
public static void copy(FieldReader input, FieldWriter output, ExtensionTypeWriterFactory extensionTypeWriterFactory)
```
Also updated ComplexCopier tests.
Closes #836.
> GH-836: Added support of ExtensionType for ComplexCopier

- ci/scripts/jni_full_build.sh
If we use absolute path, users need to create the same directory structure. It's inconvenient. We should use relative path.
Closes #592.
> GH-592: [Release] Use relative path in .sha*
